- tashibot/index.js
合成語を分解して（例えば`sandbox`=>`sand`+`box`）仮名に変換します。
可能な分割を全列挙して，なるべく少ない単語数になるような分割を選び，それぞれ仮名に変換してjoinします。アルファベット各文字の読みが登録されている関係で，全ての英単語に読みがつくはずです。
> enable kanization of compound words

- emoji-notifier/index.js
- emoji-notifier/index.test.js
emoji-notifierが「絵文字`:fuga:`が追加されました」って言うついでにそのメッセージに:fuga:でリアクションします。
現状では`icon_emoji`に:fuga:が登録されていて，そこから絵文字を見ることができますが，絵文字が一気に登録されると前のメッセージと統合されて絵文字を見ることができません（スレッドから見れないこともないですが）。あと部員がよく絵文字追加のメッセージに:fuga:でリアクションしてるのでそれが押しやすくなると思います。
> add reaction of new emoji to post of emoji-notifier

- emoji-notifier/index.test.js
#52 でemoji-notifierのチャンネルをsandboxに変更したことでテストが落ちていたので直しました。
> fix test of emoji-notifier

- achievements/index.test.ts
- achievements/index.ts
- achievements/migrate.js
- lib/__mocks__/slackUtils.ts
- lib/firestore.ts
- lib/slackMock.js
- lib/slackUtils.ts
- lib/utils.ts
- package-lock.json
- package.json
以前実績データがぶっ飛んだ事件を受けて、データが消えにくいようクラウドのDBに置くようにする。
やっぱり大切なデータをローカルのJSONファイルに置くのはよくないね❤
Loggingで昔使ってた`google_application_credentials.json`をそのまま流用できるので流用してます。
将来的にFirestoreのデータに直接アクセスしてきれいな実績閲覧ページみたいなのを作れたらいいな。
migrate.jsを実行する必要があるのでマージと同時に手動デプロイをします。
> 実績関連のデータをFirestoreに移行

- __mocks__/tinyreq.js
- lyrics/index.test.ts
- lyrics/index.ts
同じ検索クエリを投げると毎回同じ答えが帰ってくるのが微妙なため。
* axios => JSDOM を廃止し全部scrape-itに
* itunesが残ってるので全部ではなかった。まあ
* 歌詞の昇順に200件取得して、その中からランダムに選択するよう修正
> lyrics: Make result from uta-net random

- wordhero/crossword.ts
クロスワードがけっこう縦幅を取るので、「わいわい！」を毎回新規で投稿しているのを、最初の「始めるよ〜」の投稿を更新していくスタイルに変更します
最後の「残念、クリアならず」か「クリア！」は新規の投稿のままにしてあります
> クロスワードの盤面を毎回新規で投稿しない

- package-lock.json
- package.json
> upgrade jest to 25.1

- achievements/index_production.ts
- atcoder/index.ts
- atcoder/types.d.ts
- better-custom-response/index.ts
- context-free/index.ts
- deploy/index.ts
- emoji-modifier/index.ts
- emoxpand/index.ts
- lib/slack.ts
- lyrics/index.ts
- oauth/index.ts
- oogiri/index.ts
- package-lock.json
- package.json
- ponpe/index.ts
- scrapbox/index.ts
- slack-log/index.ts
- tiobot/index.ts
- tsglive/index.ts
- tunnel/index.ts
- voiperrobot/index.ts
- welcome/index.ts
- wordhero/crossword.ts
- wordhero/index.ts
各所で定義されている `SlackInterface` を `lib/slack.ts` に一本化します。
#253 が完成する前でも他のPRを手掛けてる人がこのブランチをMergeできるので， #253 における `@slack/client` 周りの修正が多少減ることを期待しています。
- `typescript` をアップデート
+ type-only import のため
- `ts-jest` をアップデート
+ `jest@25.1` に対応しているバージョンに
- 各ファイルの `SlackInterface` の定義を削除し，代わりに `../lib/slack` からimport
例えばtunnelなどは `SlackInterface` とは別に `WebClient` を使っていて，このような場合はimportはそのままにしています。 わざわざ `WebClient` を `lib/slack` でimportしてexportするのは微妙だと思ったので。これらは #253 で適切なimportに書き換えます。 `import '@slack/client'` が残っているファイルのリストは[コメント](#issuecomment-590730518)にあります。
> SlackInterfaceを共通化

- index.js
`npm run dev -- --startup 'ｳｵｳｵ（起動音）'` ができます
> allow startup sound to be specified as a command line option

- emoji-modifier/index.ts
`@emodi :otsu: | go left`みたいなのが治るはず
何のために非同期関数使ってるのかよく分かんないコードになってきたな
> emodi: fix move's jpg bug

- oogiri/index.ts
#293 oogiriの大喜利開始メッセージでBET可能枚数のところに最大意味登録可能数が表示されていたのを修正
> Fix: fixed #293

- sunrise/fetch.js
- sunrise/index.js
これまでのソースであった[e船団](http://sendan.kaisya.co.jp/)の「今日の一句」は、2020年6月15日を最後に更新が停止されたため、代わりに[俳人協会](https://www.haijinkyokai.jp/)の「今日の一句」を使用するようにしました。
> 「本日の一句」の出典を変更

- tahoiya/index.js
今までたほいやの意味登録はただそのまま入力するだけだったので、たまに被害者が発生していました（[例1](https://slack-log.tsg.ne.jp/C7AAX50QY/1590591189.496500) [例2](https://slack-log.tsg.ne.jp/C7AAX50QY/1595679615.099800)）。
そこで、意味登録方法を「たほいや hoge」に変更しました（「たほいや」の部分は変更の余地があるかも）。
あわせて、意味登録まわりの説明文も変更
> tahoiya: 意味登録方法を改善

- mahjong/index.js
進行中の配牌が忘れ去られ新たに配牌されようとしたときに、今の仕様だと進行中のゲームのスレッド内でbotがキレていました。それだと新たに配牌した人が気づきにくい（単に重いのと区別がつかない）ので、スレッドの外に投稿するようにしました。サンマも同様です。
> mahjong: ゲーム進行中に更に配牌仕様とした際の:ha:の送信先をスレッド内からスレッド外へ

- hayaoshi/index.ts
quiz.answerをreplaceして答えがおかしくなる場合を修正。
例 http://qss.quiz-island.site/abcgo-info/11300
変換前の答え: `明智光秀(あけち・みつひで)【「惟任光秀(これとう・みつひで)」「明智惟任日向守光秀」も○】`
旧: `明智光秀」「明智惟任日向守光秀」も○】`
新: `明智光秀`
> hayaoshi: 早押しクイズhardで答えの切り出し方を修正

- lyrics/index.test.ts
- lyrics/index.ts
iTunes Search API にいつの間にか Apple Music 関係のデータが含まれるようになったことに気づいたので、Apple Music のリンクを貼るようにしました。
いいなと思った曲を Apple Music ライブラリに一瞬で追加できるようになるぞ! (iPhone で押すと Music アプリが開くし、ブラウザでも可)
> 歌詞検索くんに Apple Music リンクを追加

- slack-log/index.test.ts
- slack-log/index.ts
Close #328 
これまでの slacklog-ize は `https://tsg-ut.slack.com/archives/C0123ABCD/p1501234567890123` のような canonical URL にのみ対応していましたが、各アプリで thread の message の URL をコピーすると余計なパラメータがついてきて、一発で slacklog-ize することができませんでした。
パラメータを無視することで、対応させました。
また、web と iOS の2つの client のコピー形式をテストに記述し、問題ないことを確認しました。
これでくっきーさんの日記がいっそう捗ります。喜ばしいですね。
感想:
* test が完璧なおかげで、いちいち manual test しなくても jest だけで動作検証できてすげ〜
* 一瞬これまでの正規表現でなんで動かないのかわからなくて、罠だな〜と思った (最後に `>` があるのが盲点ですね)
@cookie-s さん、レビューお願いします。
> thread について各 UI で発行される default URL の slacklog-ize 対応

- CODEOWNERS
- achievements/achievements.ts
- hitandblow/.eslintrc.json
- hitandblow/.prettierrc.json
- hitandblow/index.test.ts
- hitandblow/index.ts
- index.js
sandboxでHit & Blowができるとえらくない？えらいです（断定）
hitandblow {桁数(任意)}でHit & Blowを起動
スレッド内で{
数字をつぶやくとcall,
history/コール履歴 でcallの履歴を表示,
giveup/ギブアップ でギブアップ,
}
hbdiff {validなcall} {validなcall}（桁数が同じ）で２つのcallを比較してくれる
実績もいくつか追加
> hitandblow: Hit & Blow を実装

- package-lock.json
- package.json
最近ボイパのテストが落ちていましたね
https://github.com/zlargon/google-tts/blob/master/CHANGELOG.md#005-nov-8-2020
> Add retry mechanism to prevent fetching token key failed too frequently. (# 33)
> update google-tts-api 0.0.4 -> 0.0.5

- .github/workflows/test.yml
- README.md
Close #365.
Travis を GitHub Actions に置き換えた。ついでに workflow のファイルのキモいスペースを消した。
これ、workflow 名が Test なの、開発途中のがそのままになってるのかと思いきや、ユニットテストの「テスト」なのね。ちょっとややこしい気もするけど、まあ。
> README に GitHub Actions の status badge を追加

- pwnyaa/.eslintrc.json
- pwnyaa/index.ts
- pwnyaa/lib/BasicTypes.ts
以下の変更を行いました。
- `pwn`コマンドの追加: 常設CTF以外の問題を解いた際に、その旨を自己宣言することを可能にします。`pwn`コマンドで宣言したsolve数はweeklyのランキングに加算されます。
- usageの充実: コマンド毎のusageを`help <command name>`で見れるようにしました。
- 余分なメンションの廃止: 他のランキングに倣い、weeklyのランキングにおけるメンションを廃止しました。
- weeklyのランキングにおいて0-solveユーザを除外しました。
> pwnyaa: 自己solve宣言

- emoji-modifier/index.ts
Help documents for each filter is now on.
e.g. Post `@emodi help move` and you will get the information about the `move` filter.
The normal help message is also improved. Post `@emodi help` and you will get
>usage: @emodi <emoji> | <filter> <argument> <argument> ... | <filter> <argument> <argument> ... | ...
>Write ":" around the emoji name!
>Filters: identity speedTimes mirrorV mirror move go trim distort pro think
_Semi-destructive change: every time you implement a new filter from now on, you should add its help document, although no fatal error will happen even if you don’t do that._
> emodi help for filters

- mahjong/index.js
[動画](https://www.youtube.com/watch?v=z8eKAUTZx80)を見かけて、面白そうだったので実装してみました。具体的なルールは以下の通りです。
- サンマ
- 役満縛り（役満以外で上がると錯和）
- 数え役満あり（48000点以上かどうかで判定）
- 開いているドラ表示牌にぶつかるまでは王牌も引ける（←これは理想で、カンがないので実装としては単純にツモ回数を20にしました。）
- 350000点スタート、600000点で勝利（配牌/サンマとは別得点）
> [add] Implemented 大麻雀

- achievements/achievements.ts
pwnyaaをksnCTFに対応するに際して、専用の実績を2つ追加したいです。
> pwnyaa: ksnctf用に実績を追加

- package.json
従来の CODEOWNERS の読み方では、無駄な lint 試行が発生していました。
例えば、 `sed "s/\\/.\\+//g" CODEOWNERS | grep "^[a-z]" | xargs -n 1 echo` してみると
```
achievements/**
@hakatashi
ahokusa/**
@kurgm
anime/**
@hakatashi
...
```
となります。つまり2行に1行、invalid な入力が lint に渡されていたわけで、そのたびに
```
Oops! Something went wrong! :(
ESLint: 7.18.0
No files matching the pattern "@hakatashi" were found.
Please check for typing mistakes in the pattern.
```
などと言われていました。
この PR では、awk を挟むことによってこれを修正しています。
参考: `sed "s/\\/.\\+//g" CODEOWNERS | grep "^[a-z]" | awk '{print $1}' | xargs -n 1 echo`
```
achievements/**
ahokusa/**
anime/**
...
```
> lint スクリプトの改善

- ponpe/index.ts
attachmentの時とかに`message.text`が`undefined`なのに`message.text.startsWith()`を呼んでいたため。
> ponpe: attachmentとかでstartsWithに出るエラー解消 #299

- amongyou/index.ts
amongyouで時間関係の諸々を修正します。
- :bug: 現在時刻が30分を過ぎている場合の提示選択肢の修正
- :sparkles: 開催可否の判定で、募集開始時からの経過時間でカウントしていたのを、開催中は毎分判定
- :fire: 確度の概念を抹消
resolve #447
> amongyou: fix #447 and other time-related features

- hangman/index.js
User information is stored in `state.json` when user issues `hangman .+` command. When the specified difficulty is invalid, the information is still `state.json` and block the user.  
This commit clears the info when the difficulty is invalid.
fix #469
> hangman: fix #469: clear user info when the difficulty is invalid

- tiobot/index.ts
ライブコードゴルフ大会の企画中、planner チャンネルに貼った tio のコードが sandbox に流出するということがありました。
> Disable tiobot outside sandbox

- better-custom-response/custom-responses.ts
＊～＊を『』の外側に置くことで、表示が壊れない場合を増やした（絶対に壊さないのはむずかしそう…）
> [fix]太字インジェクションにある程度対応した

- tahoiya/index.js
- tahoiya/initdb.sql
たほいやのデプロイブロックをなくしたいです。
各状態のときには以下のように処理をします。
- `waiting`: 追加処理なし
- `collect_meanings`, `collect_bettings`: フェーズ終了時間を追加で`state.json`に追加します。再起動後は、`collect_meanings`/`collect_bettings`状態ならば`setTimeout`を再び設定します。デプロイ中にフェーズの終了時刻を終了してしまったときには、`timeExtraAddition`時間だけ追加でフェーズを続けます。
resolves #472
> たほいやのブロックをなくす

- pwnyaa/lib/TWManager.ts
- TW's csrf token format changed.
- input tag changed from `<input .../>` to `<input ...>`
- single quort became double quorts
> pwnyaa: fix bug of parse TW's CSRFTOKEN

- index.ts
`tahoiya`（通常最後にロードされる）が`loading`表示から`loaded`表示に切り替わらないまま起動が完了することがあるというバグ #506 の原因は、メッセージの更新が同期的に行われるためにその順序が逆転してしまう場合があることとみられます。そこで`lodash`の`throttle`を用いることでメッセージの更新を0.5秒に1回に制限しました。
あわせて、ロードの開始を初期メッセージの投稿が終わるのを待ってからにしました。こうしないと代わりに`throttle`内でawaitをすることになり好ましくないためです。
手元にslackbotに必要な資源を全て揃えることができなかったため完全なデバッグはできていません。
The occasional bug #506 where the loading message ceases to update saying that `tahoiya` plugin, which is usually the last one loaded, is still "loading" instead of "loaded" probably happens when the order of message updates is reversed because they are done synchronously. I use `lodash`'s `throttle` to limit the frequency of message updates to once every 0.5 second.
In addition, I programmed so that the loading process starts after awaiting the initial loading message to …
> Throttle updates of the loading message

- index.ts
Ignore duplicates in the argument array `--only` (but give notice).
For example, this change affects the result of the following command:
```
npm run dev -- --only deploy --only deploy
```
Previously it was an error. After this change, it successfully loads the `deploy` plugin only once, showing
```
[INFO] HH:MM:SS Some plugins are specified more than once. Ignore except the first for each.
```
Fixed #425.
> Fix #425: ignore duplicates in the argument array `--only`.

- room-gacha/index.ts
これまで「物件ガチャ」で始まるメッセージで発火していましたが、これだと「物件ガチャすき」のような言及メッセージでも発火してしまいます。現に時々発火してしまっていました。
というわけで、「物件ガチャ」単独でない限り、スペースが続かないと発火しないようにしました。
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/541"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> 物件ガチャの発火条件を変更

- better-custom-response/custom-responses.ts
現状の占いは機械的に「か」を見ているため、「行くか行かないか占い」の選択肢は `['行く', '行', 'ない']` になってしまっています。助詞の「か」を見るようにして、これを改良しました。十分に高速です。
配列作る部分もう少し頭のいい書き方できねえかなあと思いながらこうなったのですが、いい書き方思いついた人はレビューで教えてくださいませ。
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/558"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> 占いで品詞を見るように改良

- index.ts
なんか `loaded` もプラグインの1つみたいになってません? 太字にしたくありません? と思ったきつねであった
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/559"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Plugin の loading/loaded を太字に

- sushi-bot/index.js
- sushi-bot/index.test.js
part of #424 
うわっ、私の編集、小さすぎ...?
tsgbotくんもとからこのへんをsubscribeしてるらしいので、特にbotへの変更はいらなさそう。
DMも読めるかわかんないけど、そもそもsushi-botはDMだと動かないので関係ないです。
```
message.channels
reaction_added
reaction_removed
```
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/574"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> sushi-bot: deprecate rtm; use event-api

- lib/slackMock.js
part of #424 
getResponseのときに、eventClientのほうにも一緒にmessageをpublishする
https://github.com/tsg-ut/slackbot/pull/575 このへんでテストが落ちたため
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/577"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> lib/slack: emit message to event client in test

- atcoder/index.ts
コンテスト名の取り出し方を変更し、囲み文字が含まれないよう変更しました。
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/648"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> atcoder: コンテスト名のⒶⒽが付かないようにする

- better-custom-response/index.ts
現状の bcr は、スレッド内で発火した場合も、メインのチャンネルの方に流れてしまいます。文脈不明になる。
これを解決し、スレッド内でレスポンスを返すようにしました。また、発火の原因となる投稿が also sent to channel されている場合、レスポンスもそれに合わせます。
これらの挙動をオプションで指定できるようにしようかとも思いましたが、全部この仕様にしても問題ないのではないかと考え、そうしました。
動作確認はしてないけど多分これでええんちゃうかなと思うとります。(テキトー)
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/652"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> bcr をスレッド対応

- .github/workflows/test.yml
- package.json
これは自分本位過ぎるPRかもしれないんですが、僕いつも、たとえばwelcomeだけtestしたいとき、ローカルでだけこのpackage.jsonのパッチ入れて
```
npm test -- --testPathPattern welcome
```
とかやってるんですよね。--coverage、なんかしらないけどだいぶ重い...やってられない...
--coverageオプションを抜くことによって、ローカルでのテスト実行時間の短縮ができ、テストの機運が全体で上がるため、テストカバレッジの上昇が図れると思います！！！！！！
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/668"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> ci: split coverage into npm run test:coverage command

- amongyou/index.ts
- atequiz/index.ts
- lib/slack.ts
- lib/slackCache.test.ts
- lib/slackCache.ts
- lib/slackEventClient.ts
- lib/slackUtils.ts
- oogiri/index.ts
part of #424 
#642 の続きです rtm clientをevent client with team filterに置換します
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/676"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> lib/SlackCache: deprecate rtm

- achievements/index_production.ts
- lib/slackCache.test.ts
- lib/slackCache.ts
- topic/index.ts
メッセージにリアクションしたユーザーのIDを利用した実績を実装したい (:koresuki:がたくさんついたメッセージに最初にリアクションしたらえらい、など)
SlackCacheのreactionsCacheを「リアクション名からリアクション数へのハッシュ」から「リアクション名からリアクションしたユーザーの配列へのハッシュ」に変更した。
リアクションしたユーザーIDを保持することで、同じユーザーのリアクションが複数届いてリアクション数のカウンタがおかしくなるなどの挙動がなくなり、動作の安定性が増すのではないかと思われる。
* メモリパフォーマンスがちょっと悪くなりそう
* 配列への操作がmutableなのがちょっとキモい
* addとremoveが同じ関数なのがちょっとキモい
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/685"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> lib: SlackCache.getReactionsでリアクションしたユーザーの一覧を保持し返すよう修正

- ricochet-robots/src/main.rs
動かし方の履歴が、1 手あたり 4 ビットとして `state.log: usize` に記録していく方式だったため、16 手以上のときにバグっていた。
ということで、`Map<状態, 前回の動きと状態>` みたいなのを持っておいて、経路復元する方式で再実装する。
処理速度がだいぶチューニングされているので、一応そちらも気にしつつやってみる。
まず benchmarker.rs を以下の設定 (ハイパーロボット用) にする。それに応じて bench_correctness_check.txt も変える。
```rust
let board_h = 7;
let board_w = 9;
let wall_num = 15;
let num_of_problem = 10;
```
リリースモードでベンチマークを走らせる。
```sh
cd ricochet-robots
cargo run --release --bin ricochet_robot_benchmarker
```
3 回ほどやってみて、その中央値を記録していくことにする。
変更する前は手元の PC で 3.665s だった。
- とりあえず経路復元: 6.838s
- `res` をなくした: 6.474s
- `log` をなくした: 5.949s
- `board` をなくした: 5.604s
- `PartialEq`, `Eq`, `Hash` をデフォルト実装にした: 5.480s
- `Optional<Prev>` にした: 5.580s
- `gone` をなくした: 4.793s
- ~~`Prev` の `serialize`/`deserialize` をやめて単純な `struct` にした: 4.570s~~
- ~~`u8` → `i8`, `usize`: 5.080s~~ …
> ricochet-robots: fix path reconstruction

- octas/index.ts
- バグの内容: octasの対戦終了後の`Halt`が呼び出されておらず、2戦目以降ができない状況になっていた
- 原因: p-queueへaddされた関数の中で更に`que.add`をawaitすると、p-queueがデッドロックに陥る
- 修正内容: いくつかのawaitを消した
> [fix] octas中のデッドロックの修正

- kirafan/quiz.ts
出題範囲を有名作品や原作衣装に限ってほしいというご要望を受け、1235枚あった出題範囲を89枚の☆3キャラクターに制限したきらファン当てクイズ easy を実装しました。
☆3キャラクターのイラストにはきららファンタジアに参戦している37作品のうち初期に実装された11作品(ひだまりスケッチ、ゆゆ式、がっこうぐらし！、Aチャンネル、きんいろモザイク、NEW GAME!、ステラのまほう、うらら迷路帖、キルミーベイベー、桜Trick、ブレンド・S、スロウスタート、けいおん！)の、原作に登場したイラストが用いられています。
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/703"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> きらファン当てクイズ easy

- anime/anison.js
- lyrics/index.ts
- バグの内容
anime/anison が内部で使用している lyrics の getMovieInfo がうまく作動していない
- 原因
アニソン当てクイズ正解時に表示されるmovieのURLをlyricsのgetMovieInfo関数により取得しているが、Uta-Netの仕様変更によりhtmlの形式が変わったためうまくスクレイピングできていなかった
- 修正内容
1. スクレイピングする箇所を変更。 これに伴い、今まではgetMovieInfoは動画タイトルの情報や関連動画の情報も得ていたが、目的の動画のURLのみを返す関数になった。
2. getMovieInfoの戻り値を配列でなくしたため、anime/anison.jsにも若干の変更を加えた。
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/709"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> アニソン当てクイズが動かない問題の修正

- lib/slackMock.js
slackMock.js の handleWebcall で、chat.postMessage は無視されてたんですが、（なぜか）AteQuiz では ts: string が帰ってこないと assert で落ちるようになってるので、そっちを消すよりはということで簡易的に ok と ts だけ返すようにしました。
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/711"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [add] postMessage に対して {ts} を返すようにした

- pocky/index.js
- tahoiya/index.js
Resolve #731 
* https://api.slack.com/methods/chat.postMessage
> Set to true to post the message as the authed user, instead of as a bot. Defaults to false. Cannot be used by [new Slack apps](https://api.slack.com/authentication/basics). See [authorship](https://api.slack.com/methods/chat.postMessage#authorship) below.
* https://api.slack.com/authentication/quickstart#public
* ```
{
"bot": "index",
"error": {
"code": "slack_webapi_platform_error",
"data": {
"deprecated_argument": "as_user",
"error": "invalid_arguments",
"ok": false,
"response_metadata": {
"acceptedScopes": [
"chat:write:bot"
],
"scopes": [
...
]
}
}
},
"level": "error",
"message": "unhandledRejection at: [object Promise] reason: An API error occurred: invalid_arguments",
"promise": {},
}
<a …
```
> rm as_user in postMessage

- context-free/index.ts
AsIs
`肌: <p style="padding-bottom: 10px;">読み方：はだ 人のからだを覆う表皮。`
ToBe
`肌: 読み方：はだ 人のからだを覆う表皮。`
> Remove html tag from meaning of context-free

- golfbot/index.ts
Ref: #771
Firestoreに対する書き込みの統計を取ったところ、特にgolfbotの使用量が多い模様。
```
Firestore usage at Tue Dec 06 2022 22:00:00 GMT+0900 (Japan Standard Time): Map(12) {
'state_golfbot_get' => 112,
'state_golfbot_update' => 112,
'achievements_U017Z5N3947_get' => 1,
'achievements_U017Z5N3947_update' => 1,
'achievements_UA47NQ9GV_get' => 2,
'achievements_UA47NQ9GV_update' => 2,
'state_atcoder_get' => 2,
'state_atcoder_update' => 2,
'achievements_U02EHTGAH9P_get' => 2,
'achievements_U02EHTGAH9P_update' => 2,
'achievements_U010FS4BPKR_get' => 4,
'achievements_U010FS4BPKR_update' => 4
}
```
filter関数による代入は常にstateに対する書き込みを実施するため、filterされるものが存在する場合のみ実行するように修正しました
> golfbot: Reduce database writes by introducing state checks

- discord/index.ts
join, leave の際、同じroomへの/からの join/leave かどうかを判定せずにバグが生まれていたため、バグがないmoveと同じくactionName に roomId を付加して判定する形に修正
> join, leaveのactionNameにroomIdを追加するように修正

- api/index.ts
- index.ts
- lib/logger.ts
Fastifyのloggerオブジェクトに渡すために必要な `fatal`, `trace`, `silent` の3つのログレベルを追加。
ついでに、デバッグ環境でログが送出されたbotを表示するよう修正。
↓こんな感じ
> Fastifyのログをloggerでキャプチャできるよう修正

- character-quiz/index.ts
characterNamesには & を含んだままの名前を設定し、namePartsList で & を取り除くようにした
> &で二人以上並んでいる場合に、一人目しか正解に表示されていなかったのを修正

- character-quiz/index.ts
「名字A 名前A&名字B 名前B」という項目に対して、「名字A名前A」が正解リストに含まれていなかった
> character-quiz: & を含む項目の正解にフルネームが含まれていなかったのを修正

- context-free/index.ts
Resolves #886.
#886 での投票結果、context-free-botの頻度を減らすことになりました。このプルリクはその実装になります。
> context-free-botの投稿頻度を10分の1に変更

- .env.example
- discord/hayaoshiUtils.test.ts
- discord/index.ts
- discord/notifier.test.ts
- discord/notifier.ts
sandboxに対するdiscord通知が多すぎるという問題を受け、sandboxに対するdiscord通知をする際、同じチャンネルのものについては1つ前のものを削除するよう修正しました。また、discord通知専用チャンネル#_discordを設け、そちらにDiscordの完全なログが残るようにしました。
> Discord通知を#_discordにも流すように修正 & sandboxに対する1つ前の通知を削除するよう修正

- welcome/index.ts
welcomeが来たときに↓みたいにリンクの展開が長くて分かりにくいため
> Welcomeメッセージを送信する際にリンクをunfurlしないように設定

- atequiz/index.ts
- ricochet-robots/SinglePlayRicochetRobot.ts
- ricochet-robots/board.ts
- ricochet-robots/image.ts
- ricochet-robots/index.test.ts
- ricochet-robots/index.ts
1人プレイのハイパーロボットをスレッド化した
* スレッド化した1人プレイのハイパーロボットのロジックを新たなクラス SinglePlayRicochetRobot に実装し、ricochet-robots/index.tsから呼び出した
* ricochet-robots/index.tsにある1人プレイのコードはとりあえず残してある (そのうち消す)
* answerMessageGenでanswerMessageを動的に生成できるようにした
* solvedMessageGenをasync関数でオーバーライドできるようにした
* 最初のメッセージをもう一度投稿するrepostProblemMessage関数を実装した
> ハイパーロボットをスレッド化

- topic/index.test.ts
- topic/index.ts
Slackのtopicの長さ制限がいつの間にか250バイトから250文字になっていたので、最大でその長さまで使い切るよう修正
ついでにtopic入りする発言の長さ制限を100バイトから60文字にした (日本語の場合約1.8倍の長さまで緩和)
> topic: topicの長さ制限の仕様変更に対応

- achievements/achievements.ts
- pwnyaa/index.ts
- pwnyaa/lib/AHManager.ts
pwnyaaを AlpacaHackに 対応す
昼飯食べたら セルフマージする... (心の俳句) 
Closes #930
> pwnyaa: AlpacaHack 対応

- city-symbol/index.ts
> city-symbol: Add more information to answer message

- sushi-bot/index.test.js
- sushi-bot/index.ts
うまく push できなかったので PR を建て直しました
"Twitter" を含むメッセージに対して "X" スタンプが来るのに対抗して，"X"（単語中のものは含まない）を含むメッセージに対して "Twitter" スタンプを送るようにしました
> "X" 発言に Twitter スタンプを送る

- atequiz/index.ts
- city-symbol/index.ts
- lib/utils.ts
問題出題から45秒後、ChatGPTヒントが表示されるようにした。
ついでに市町村名に `|` が含まれてしまう問題を直した。
> city-symbol: Implement ChatGPT hints

- city-symbol/index.ts
- 都道府県ごとの解答・ノーヒント解答・ノーGPTヒント解答カウンターを追加
- 都道府県指定のゲームでの解答は、県名ヒントありでの解答という扱いに
- `result.state === 'solved'` でなくても博多市カウンターがインクリメントされていたのを修正
> city-symbol: 実績用カウンターの追加・解除条件の修正

- nmpz/index.ts
* 最後のヒントから正解発表までの時間を 30s -> 90s に延ばしました
* それに伴い、トータルの時間制限が 90s から 2 * 30 + 90 = 150s に伸びます
> nmpz: extended time limit (90s -> 150s)

- pwnyaa/index.test.ts
- pwnyaa/index.ts
pwnyaaのユニットテストが落ちる問題を修正
* おそらく #931 を実装した際にテストコードの修正を行わなかったことが原因と思われる
* updateAllが非同期的に実行され、そこでエラーが発生していたため、updateAllが実行されるタイミングまでにユニットテストが終了するかどうかによって今までランダムにテストが失敗していた
* テストをAlpacaHack追加に合わせて修正した
* 初期化時にupdateAllをawaitすることにより、テスト始動時にupdateAllが同期的に実行されることを保証
* これにより本番環境でのslackbot起動までの時間が通常より長くなるが、いたしかたなし
> Fix pwnyaa unit test degration from #931

- .gitattributes
現状、package-lock.jsonは git diff などの出力で不必要に行数が多く表示されないようにバイナリ比較されるが、以下のようなデメリットがあるためこれを解除する
* WindowsとUnix系OSなど、改行コードの異なるシステム間でファイルを編集した際にファイル全体が置き換わった扱いになる
* sub-dependenciesの更新など、package-lock.jsonの変更をレビューしたいこともある
> fix: remove package-lock.json from binary attributes

- deploy/index.ts
This reverts commit e4c69c27593016432131761b267583cba31d30b8.
Pointer Compression はすでに使用していないため、デプロイプロセスの簡略化のためrevert
> Revert "Pointer Compressionと互換性を持つようにデプロイコマンドを変更"

- .github/copilot-instructions.md
- helloworld/HelloWorld.test.ts
とりあえず作成。
GitHub公式の見本ファイルと、[DeepWiki](https://deepwiki.com/tsg-ut/slackbot)のドキュメントをCopilot自身に食わせて作成した雛形を元に、手作業でレビューし修正を加えた。
HelloWorldボットの書き方を参考にしてほしいため、そちらも若干修正を加えた。
GitHub Docs: https://docs.github.com/ja/copilot/how-tos/agents/copilot-coding-agent/best-practices-for-using-copilot-to-work-on-tasks#adding-custom-instructions-to-your-repository
> Add GitHub Copilot instructions

- lib/eventClientWrapper.test.ts
- lib/eventClientWrapper.ts
- lib/eventDeduplication.test.ts
- lib/eventDeduplication.ts
- lib/slack.ts
- lib/slackCache.ts
- lib/slackEventClient.ts
Fixes #1028.
Regression by #1015.
TeamEventClientクラスは複数のインスタンスが作成されるため、イベント重複除去が複数行われ、除去するべきでないイベントが除去されてしまう不具合が存在した。
EventClientをラップするEventClientWrapperクラスを作成し、TeamEventClientにあったイベント重複除去処理をこちらに実装した。
TeamEventClientは #1015 以前のコードに戻した。
ついでに、DuplicateEventCheckerのRedisとの通信がアトミックでなかったので、SETのNXオプションを用いて単一コマンドで処理するようにした。
> イベントの重複除去処理をEventClientWrapperクラスに移動

- auto-archiver/index.test.ts
- auto-archiver/index.ts
Resolves #1027.
ついでによくなさそうな部分を諸々修正。
at channel を投げるBOTを気軽に手元で起動させてはいけない (1敗)
> auto-archiver: conversations.listのページネーションを適切に処理するよう修正

- achievements/index_production.ts
「最初にリアクションする」実績が達成されない問題がこれで直ってほしいが、果たして
> achievements: Add delay to allow slack-patron to cache reaction data

- context-free/index.ts
1. 単純にBOTの趣旨に反していそうなため
2. 「他人のポスト」などを解除条件とする一部の実績の趣旨が満たされない可能性があるため
> context-free: 置き換え部分の存在しないポストの投稿を拒否

- tahoiya/index.js
`https://www.weblio.jp/content/%E5%BD%A6%E9%A0%81?dictCode=INGDJ%7Chttps://www.weblio.jp/content/%E5%BD%A6%E9%A0%81?dictCode=INGDJ`
みたいな感じに`%7C`挟まり２回コールされる現象が2025/８月下旬から発生
slackのURLの使用で`<http://hoge.com|description>`みたいなのが変数urlに格納されているが，後ろ側も`http://hoge.com`になった場合上記の感じになる。なぜ突然うまくいかんくなったかは不明だが，前後の`<>`を取り除くだけではなく，`<〜|`または`<〜>`の間を取るようにすれば良い。
> url handling fix of tahoiya

- index.ts
9月13日23時頃のslackbot再起動以降、slow-quizの状態が11日10時～12日10時のどこかの状態に巻き戻ってしまう現象が発生した。
原因としてはおそらく[Firestoreの1MB制限](https://stackoverflow.com/q/49144258/2864502)に引っかかったものと見られ、解決するには現在レプリケーションとして使っている `slow_quiz_games` をマスターデータにしてstatesにgamesを状態として持たないようにする必要がある。
すぐには直せなさそう、かつ復旧するまでslow-quizボットへの書き込みは無効化されてしまうと思われるので、復旧するまでの間slow-quizボットを無効化しておくことにした。
> slow-quizボットを一時的に無効化
