tsg-ut/slackbot

package.json
shogi/index.js

- `[右左直]?[寄引上]?`に対応しました
- エラーメッセージを書きました

[右左直]?[寄引上]?

---

package.json

escape wildcard

---

prime/index.js

challengerにuseridを保存します。
あと、なんかたとえば間違ってslackbotみたいなのが素数大富豪権を握られるとDoSみたいになるので、@primebot resetというバックドアを叩くと任意の人間がリセットできます

save challenger

---

tashibot/index.js

bep-eng.dicの1行目が`-*- coding: shift_jis -*-`みたいになっていて，それが英語->カタカナ辞書に混じっていたので直しました。ついでにbep-eng.dicを読むときの文字コードが明示されているもの（上の例なら`shift_jis`）になるようにしました。

handle encoding specification in bep-eng.dic

---

__mocks__/node-persist.js
package-lock.json
package.json
sunrise/__mocks__/fetch.js
sunrise/__mocks__/render.js
sunrise/fetch.js
sunrise/index.js
sunrise/index.test.js

sunrise: Add test

---

index.js
jest.config.js
package-lock.json
package.json
sunrise/index.test.js
tiobot/index.test.ts
tiobot/index.ts
tsconfig.json

tiobot: TypeScript

---

index.js
welcome/index.ts

welcome: add welcome bot

---

welcome/index.ts

welcome: post to general

---

slack-log/index.ts

slack-log: fix for undefined text

---

welcome/index.ts

Welcome in DM

---

wordhero/index.ts

wordhero: owari

---

sushi-bot/index.js

sushi-bot: fix wednesday-sushi

---

tahoiya/index.js

tahoiya: Fix rating bug :bug:

---

sushi-bot/index.js
sushi-bot/index.test.js

implement '寿司ランキング 確認'

---

sushi-bot/index.js
sushi-bot/index.test.js

"凍結ランキング 確認" で凍結回数と順位を見られる機能を実装

Implement "凍結ランキング 確認"

---

package-lock.json
package.json

Windowsでも動くようになったはずです
https://travis-ci.org/pizzacat83/node-word2vec

move word2vec from optionalDependencies to dependencies

---

deploy/block.js
deploy/block.test.js
deploy/index.ts
mahjong/index.js

deploy block

---

ahokusa/index.js
ahokusa/index.test.js

:sushi-6-3-1::sushi-6-0-1::sushi-6-2-2::sushi-6-5-5::sushi-6-5-1::sushi-6-5-2:
:sushi-6-0-3::void::sushi-6-1-5::sushi-6-0-2::sushi-6-3-2::sushi-6-0-0:
:sushi-6-3-4::sushi-6-4-1::sushi-6-1-0::sushi-6-2-0::sushi-6-2-4::sushi-6-5-4:
:sushi-6-4-2::sushi-6-3-5::sushi-6-0-5::sushi-6-1-2::sushi-6-1-1::sushi-6-4-4:
:sushi-6-2-1::sushi-6-4-0::sushi-6-2-5::sushi-6-0-4::sushi-6-3-0::sushi-6-4-5:
:sushi-6-2-3::sushi-6-3-3::sushi-6-1-4::sushi-6-4-3::sushi-6-5-3::sushi-6-5-0:

Sushi puzzle

---

sushi-bot/index.js
sushi-bot/index.test.js

public sushi count

---

deploy/index.ts

deploy: await setTimeout

---

tashibot/scraper/package-lock.json
tashibot/scraper/package.json

update dependency packages by tashibot scraper

---

.env.example
index.js
oauth/index.ts

Slack App のインストール時にリダイレクトされるエンドポイントです

Implement oauth

---

sushi-bot/index.js

Fix many rankings on weekend

---

index.js
package-lock.json
package.json
voiperrobot/index.js
voiperrobot/index.test.ts
voiperrobot/index.ts
voiperrobot/mutex.test.ts
voiperrobot/mutex.ts

Voiper robot

---

tashibot/index.js

次のバグが修正されます:
- 出発駅(1つ目の駅)と2つ目の駅の間の距離（と運賃）が考慮されない
- 実際には2つ目の駅で乗り換えが発生する場合に，乗り換えにならない

tashibot: Fix first edge bug

---

shogi/index.js

:ha::korosuzo:
がスレッドに投稿されるようになると思います。

shogi: post :ha: :korosuzo: in thread

---

achievements/achievements.ts
achievements/index.ts

add :seyana: and any reaction count

---

tunnel/index.ts

tunnel: fix channel id

---

tunnel/index.ts

tunnel: swap tsg and kmc

---

tunnel/index.ts

ユーザートークンの `emoji:read` 権限が必要です。多分現時点ではトークンに権限がついてないので，TSGとKMCのユーザートークン保持者(@hakatashi , @cookie-s ?)にアプリのreinstallをしてもらう必要があります。トークンの文字列は変わらないっぽいので，環境変数の変更等は不要だと思います。

tunnel: use image of emoji

---

wordhero/index.ts

wordhero: lighter memory for trie tree

---

.env.example
README.md

Update README.md and .env.example

---

achievements/achievements.ts
voiperrobot/index.test.ts
voiperrobot/index.ts

Add voiperrobot achievements

---

prime/index.js

prime: Fix 合成数出し bug

---

achievements/achievements.ts
package-lock.json
package.json
ricochet-robots/board.js
ricochet-robots/image.js
ricochet-robots/index.js
ricochet-robots/index.test.js
ricochet-robots/rust_test_output.txt
ricochet-robots/src/main.rs

Mutexにしたおかげで実績を実装できるようになった(ハズ)です。
(achivement関連のテストはできてませんが...)(やっといたほうがいいですかね?/やるとしたらどうやって?)

Ricochet robot/mutex

---

achievements/achievements.ts
ricochet-robots/index.js

というわけで足しました。(自分のbotのachivementならこれ以降勝手にマージしちゃっていいかんじですか)

add achivement for ricochet robot & change achivements condition

---

ricochet-robots/index.js

fix mutex release bug

---

ricochet-robots/index.js

fix too depth bug

---

checkin/index.js
pocky/index.js

Fix ReferenceError: logger is not defined

---

ahokusa/index.js

wasd to hjkl de ugokeru youni natta kamo

add wasd and hjkl move to ahokusa

---

sunrise/index.js

夜明から日暮までの間「今何時」の答えがバグってたのを修正しました

Fix sunrise bug

---

achievements/achievements.ts
ahokusa/index.js
ahokusa/index.test.js

add achievements for ahokusa sliding puzzle

---

ahokusa/index.js

add more hakka condition

---

wordhero/index.ts

wordhero: a bit faster

---

slack-log/index.test.ts
slack-log/index.ts

slacklog: fix slacklog-ize

---

slack-log/index.ts

slacklog: Unfurl links in slacklog command response

---

wordhero/LOUDS_builder/build.py
wordhero/index.ts
wordhero/trie.js

Wordhero: use LOUDS

---

shogi/index.js

将棋の強制再起動機能

---

achievements/achievements.ts
tahoiya/index.js

Slackbot初心者です
お手柔らかによろしくお願いします

add an achievement of winning first place in tahoiya

---

achievements/achievements.ts

fix 5:ナンやねん-ナンなので: achievements ...?

achievement id ni zenkaku moji haittete iindesuka

---

sunrise/fetch.js
sunrise/index.js

the end of 'today's ikku'

---

atcoder/index.ts

atcoder: author_link

---

CODEOWNERS
ojigineko-life/index.js

ojigineko-life: 30min

---

shogi/image.js

sharpのアップグレードでoverlayWithが消えたためにshogiくんが動かなくなっていたっぽいです
試してないけど動くやろ！ｗ

shogi: overlayWith -> composite

---

ojigineko-life/.gitignore
ojigineko-life/index.js

ojigineko-life: Good ojigineko sleep at night

---

mahjong/index.js

打:nanyanen-nannanode:で打南ができるようにしたい

enable cutting :nanyanen-nannanode:

---

sushi-bot/index.js

implement asa-scoring as part of sushi-bot

---

sushi-bot/index.js

なおした！！！:ahokusa-top-right::ahokusa-bottom-left::heavy_exclamation_mark: とかに対応したはず！！！

manage alias expressions for asa-scoring

---

tunnel/index.ts

fix #87 
fix #88 
fix #94 
コンパクトになりました！（最大50行→10行）
イメージ: https://tsg-ut.slack.com/archives/C7AAX50QY/p1566551485268900

tunnel: small reaction

---

package-lock.json
package.json
tunnel/index.ts

[これまで](https://tsg-ut.slack.com/archives/C7AAX50QY/p1566553964293700)カスタム絵文字はマウスオーバーでリアクションした人を見ることができましたが，非カスタム絵文字は絵文字の名前のみでした。
非カスタム絵文字もマウスオーバーでリアクションした人を見ることができるように[なりました](https://tsg-ut.slack.com/archives/C7AAX50QY/p1566556419383500)。:waiwai:

tunnel: support non-custom emojis

---

better-custom-response/custom-responses.ts

- :nya-n:リアクションの正規表現を豊かにしました
- `@tsgcat`を実装しました

better-custom-response: implement original tsgcat

---

.gitignore
emoxpand/.gitignore
emoxpand/index.ts
tsconfig.json

テストない問題はあるんですけどfastifyのモックがなかったりしてつらいのではの気持ちになっています

Add emoxpand

---

index.js

require('./emoxpand')

---

emoxpand/index.ts
lib/slackUtils.ts

enable retrieving finer icons with getMemberIcon

---

CODEOWNERS

I forgot to modify this when creating the bot

CoiL is the author of emoxpand && Naan is the author of bcr

---

better-custom-response/custom-responses.ts

add custom responce really?

---

better-custom-response/custom-responses.ts

Fix bcr for 本当に〇〇でいますか?

---

emoxpand/index.ts

sig-beginnersの人々がフロントエンドを作ってくれると聞いて

hyper zatsu list api

---

better-custom-response/custom-responses.ts
better-custom-response/index.ts
better-custom-response/responses/hontouni.ts

Tokenize 本当に? response and return only 語幹 for response

---

index.js

メモリ300MBくらい食ってた記憶があり，最近crosswordの度にslackbotが落ちるので一旦無効化したいです
時間ができたらvocabwar改善するつもりなので，とりあえずそれまでおやすみさせていただきたく

:wave: vocabwar

---

.env.example
index.js
lib/slack.ts
lib/slackUtils.ts
oauth/tokens.d.ts
tunnel/.eslintrc.json
tunnel/index.ts

KMCトンネルのユーザー名・アイコン・リアクションが最新の情報になるよう修正

---

anime/index.js

state.hints.length === 1および2のとき、2回以内, 3回以内の実績を解除するように

nikai tte sankai inai ja nainsuka :ikku:

---

anime/index.js

`@anime title` でランダムなサムネイルが取れるようになりました！ :waiwai:
動作テストは、していません...

add `@anime title`

---

index.js

require('./sort-nazonazo')

---

ojigineko-life/index.js

でも、なにもかも...変わらずにはいられないです。
楽しいこととか、うれしいこととか、ぜんぶ。
ぜんぶ、変わらずにはいられないです。

ojigineko-life: 諸行無常

---

slack-log/index.ts

slacklog: use display_name

---

tahoiya/index.js

テストしようと思って「たんご/たんご/たんご/たんご」たほいやゲームしてたら、betしたあとにassertで落ちてもうテスト無理ってなったんで動くやろの精神
```
{"message":"AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:\n\n  assert(source === 'nicopedia')\n\n    at module.exports.getWordUrl (/home/cookies/tsg/slackbot/tahoiya/lib.js:72:2)\n    at onFinishBettings (/home/cookies/tsg/slackbot/tahoiya/index.js:502:30)\n    at process._tickCallback (internal/process/next_tick.js:68:7)","level":"error","timestamp":"2019-11-03T06:59:25.411Z"}
```

tahoiya: deploy block

---

checkin/index.js

not to display if lastname is Undefined

---

sort-nazonazo/index.js

- 開始時にスレッドを立てる
- 答えの URL ではなくページタイトルを表示

Improve ソートなぞなぞ

---

mail-hook/index.js
mail-hook/index.test.js
package-lock.json
package.json

:kokoha_dehanai3::crypto:
テストしてないけど、動くやろ！ｗという気持ち
ところでちゃんとメールのContent-Typeヘッダでエンコーディングを見るべきという説はある

iso-2022-jpのメールをデコードする

---

anime/anison.js
lyrics/index.ts

add a new achievement 

---

welcome/index.ts

welcome botのユーザー名とアイコンの変更

---

context-free/index.ts

@cfb response

---

CODEOWNERS

emodiとか私一人でいじるとメモリ破滅しそうだし人に見てもらいたい気はするんですがとりあえず

modify cfb, emodi's owner

---

emoji-modifier/index.ts

色数を落とすやつが重かったようで、フレームごとの処理を直列にするとマシになるようです

Quantize sequentially

---

sunrise/fetch.js
sunrise/index.js

This reverts commit 853130d0dab404fdd39acceb07456bedefb3e760.
* 未テストです
* また6月に削除することになりそうです :cry:
> 2001年1月1日からスタートしたe船団。2020年6月をもって終了します。
(http://sendan.kaisya.co.jp/)

Revert "the end of 'today's ikku'"

---

context-free/index.ts

`/cfp {uo} is {uo} but not {}`みたいなのでプレースホルダを置換します

cfb: context free post

---

context-free/index.ts

cfp: Escape RegExp

---

sunrise/fetch.js

「今日の一句」のページのHTMLが若干変わっていたせいで句が出ていなかったのが治るはず?

Sunrise: Deal with HTML structure change

---

achievements/achievements.ts

GitHubのリポジトリ下でPRにReviewをするとほめてもらえます

achievements: add new achievement `github-review`

---

emoji-modifier/index.ts

これに限った話ではなく:ojigineko:などで挙動が変なのは既知で、気が向いたら治します
色々雑だけどまぁええやろ

add filter pro

---

lib/loadFont.ts
package-lock.json
package.json
wordhero/render.ts

* よく使うNoto serifをデフォルトにする(現状)か今呼んでるところをいじってフォントを指定させるのどっちが良いのかなぁと思っています
* そもそも使うときに毎回URL指定するのめんどいし名前と紐付けるとかした方が良いのか? とも思っています

generalize loadFont to load other fonts

---

sunrise/render.js

sunrise: fix loadFont invocation

---

sushi-bot/index.js
sushi-bot/index.test.js

https://www.jma.go.jp/jma/kishou/know/yougo_hp/saibun.html に従って6時から9時の間は100点、あとはいいかんじになめらかに採点するようにしました。

revise asa scoring

---

achievements/index_development.ts
achievements/index_production.ts

リアクションが付いた時に該当メッセージへのリンクをつけるなど用です

allow achievements to show additional info when unlocked

---

emoji-modifier/index.ts

結局wordhero方式にしました レイアウトとかもうちょい調整してもいいけどとりあえず動くやろで

Emodi: Fix pro font issue

---

emoji-modifier/index.ts

emodi: remove _.escape

---

achievements/.eslintrc.json
achievements/index_production.ts

実績解除の表示をコンパクトに

---

emoji-modifier/index.ts

雑にPromise.allしたとこTSG鯖で動くか若干不安だけどとりあえず

implement filter distort

---

emoji-modifier/index.ts

process rows sequentially

---

achievements/achievements.ts

Reaction achievement '海藻を買いそう' for :kombu: is added.

Adding reaction achievement for :kombu:

---

CODEOWNERS
lyrics/index.ts

* iTunes をスペルミスしていました (これめっちゃ笑った)(誰か気づけや)
* code owners に自分を入れていなかったので入れておきました
* コードのスタイルを微修正しました

lyrics の些細な修正

---

achievements/achievements.ts

idはデータベースいじるのがめんどくさそうだしいいかなと思っています

fleshpeach -> freshpeach

---

achievements/index_production.ts

テストしてないけどこれは動きます。スーパークリエイターが言うんだから間違いありません。

achievements: Update info of users when member joined channel

---

ahokusa/index.js

テストしてないけど盤面追加しただけやし動くやろ〜(ガッハッハ)

add chiya slide puzzle

---

achievements/achievements.ts
ahokusa/index.js

add chiya slide puzzle achievements

---

ahokusa/index.js

add new achievement

---

index.js

#274 
悪い子はいねが～
`ERR_AVVIO_PLUGIN_TIMEOUT` のあとに `Launched` のログが出ているので、だれかがわるいんじゃ。

log time of end of each plugin load

---

achievements/achievements.ts

add 5:masaka-sakasama: achievement

---

better-custom-response/custom-responses.ts

toronto => :sushi-toro:などと反応します
サーモンだけスペリングが特殊なので分けてます

bcr: add sushi reaction

---

slack-log/index.ts

`slacklog hoge @hogefugatsg #hogefuga` などと発言するとそれに対応した検索URLを出してくれます

Implement slack-log search util

---

achievements/achievements.ts

アニソン当てクイズhardのバグ修正（というか本来の形にした）

add the achievement 'anime-song-hard-answer'

---

atcoder/index.ts

atcoder: Fix precondition to unlock atcoder-all-solve

---

achievements/achievements.ts

achievements: Add hakatashi-typo

---

index.js
jitsi/.eslintrc.json
jitsi/index.ts
package-lock.json
package.json

Implement Jitsi

---

__mocks__/fs.js
ponpe/index.test.ts
sushi-bot/index.js
sushi-bot/index.test.js

[需要が](https://slack-log.tsg.ne.jp/C7AAX50QY/1596363772.214400)[あるっぽい](https://slack-log.tsg.ne.jp/C7AAX50QY/1596363919.220100)ので?
* `max`って関数名なんとかならんのかとは思っています
* jsonに毎回書き込む関係でテストでrace conditionが発生しがちっぽかったので毎回jsonを消すことにしたんですが、あんまり根本的な解決になってない気もしています

あさ！点数ランキング

---

achievements/achievements.ts
sushi-bot/index.js

asa achievements

---

wordhero/render.ts

This reverts commit 9204dc3dc55b380bbcb5a913e8e9a36d40bd66c5, reversing
changes made to f2fa5797a943fbfda7a3a043e3a7b12b1acb141b.

Revert "Merge pull request #311 from tsg-ut/change-density"

---

better-custom-response/custom-responses.ts

`:question:` と送ると `:exclamation:` と返すレスポンスを追加しました。確率で `:exclamation_w:` と返ってきて微妙な気持ちになれます。

bcr: add Hugo's shortest conversation

---

achievements/achievements.ts
sushi-bot/index.js

108 mawari achievements

---

achievements/achievements.ts
sushi-bot/index.js

起床ランキング: 同率タイのとき実績が解除されないよう修正

---

index.js

2分以内の再接続が連続しているとみなされ、数えられます
幅は適当なので異論があれば

count reconnection combo

---

better-custom-response/custom-responses.ts

BCRを一つ追加しました
「デニム」が含まれるメッセージに反応します
よろしくお願いします

added BCR (trigger: "denim")

---

better-custom-response/custom-responses.ts

Revert "added BCR (trigger: "denim")"

---

better-custom-response/custom-responses.ts

4行目を更新し、手元でエラーを吐かなくなったことを確認しました。

Inserted header for shuffle

---

better-custom-response/custom-responses.ts

Revert "Revert "added BCR (trigger: "denim")""

---

context-free/.eslintrc.json
context-free/index.ts
emoji-modifier/.eslintrc.json
emoji-modifier/index.ts
emoxpand/.eslintrc.json
emoxpand/index.ts

.eslintrc.jsonを置いて、`npx eslint`かけてもエラーは出ないようにしました
挙動を変えるようなことはほぼしてないはず?
私がownerのとこだけいじったのでテスト通ったらマージするんですが、なんかバグったらごめんなさい

CoiL製botをeslintする

---

mahjong/index.js

mahjong botで[一二三四五六七八九][萬筒索]を宣言する時に1m, 3pのような表記ができるように

mahjong simple hai name

---

mahjong/index.js

リーチ hogeのhogeにはアルファベット表記からの変換やナンアイコンからの変換がなされていなかったので、なおしました

mahjong: 操作のアルファベット/ナン表記の仕様変更

---

twitter-dm-notifier/index.ts

全然 DM こーへんし15分とかでよくない? いいよ ありがとう

Twitter DM 確認頻度を2分おきから15分おきに

---

achievements/achievements.ts

クロスワード・フリースインガーの説明文を改善

---

wordhero/src/bench.rs
wordhero/src/main.rs

デプロイ時に Rust の警告が出るのが気になったので……
もとのコードの意義があまり良くわかっていないので、まずい変更だったら却下してください。

Avoid wordhero warnings

---

lib/logger.js

テストのときに、つながらないsyslogにつなごうとして永遠にpromiseが解決されなくて、jestが終了できなくなっていました

logger: disable syslog in dev

---

sushi-bot/index.js

エクササイズランキングの順位集計表示の修正

---

hitandblow/index.ts

[update] 正解時に手数も表示するように

---

package-lock.json
package.json
voiperrobot/index.ts

Update google tts api

---

better-custom-response/custom-responses.ts

bcr: あほくさresponseをあほくさの任意の並びに対応

---

pocky/index.js

- ポッキーゲーム中のノーマルポッキーがポッキースレッドになることを修正ポッキー #359 
Fixes #359.

fix pocky: ポッキーゲーム中のノーマルポッキー投稿先

---

package-lock.json
package.json

vocabwarで使われていたが、彼はもういないので消します
(#393 のCIのエラー原因っぽい？)

uninstall word2vec

---

achievements/achievements.ts

pwnyaaで`pwnable.xyz`に対応するのに伴い、XYZの実績を追加したいです。

achievement: pwnyaa: xyzの実績を追加

---

pwnyaa/index.ts
pwnyaa/lib/TWManager.ts
pwnyaa/lib/XYZManager.ts

- `check`コマンドをメンション無しでSlackのユーザ名のみで可能にした
- DoS防止のセーフコードを入れた

dev-pwnyaa: checkコマンドをメンション無しで

---

pwnyaa/index.ts

pwnyaa: fix off-by-one error

---

pwnyaa/.eslintrc.json
pwnyaa/.gitignore
pwnyaa/index.test.ts
pwnyaa/index.ts
pwnyaa/lib/XYZManager.ts

pwnyaaに軽微な修正を行いました
- 日付のパースのミスの修正
- クロールタイミング及び実績解除のタイミング変更

pwnyaa: 日付パースの修正

---

pwnyaa/index.ts
pwnyaa/lib/BasicTypes.ts
pwnyaa/lib/XYZManager.ts

以下の修正を行いました。
- :pwn: 絵文字のタイポ
- XYZにおける時刻のパース
- 時刻表示をJSTに変更
- 進捗確認を12時間毎の定時に変更
テスト通り次第self-mergeします。

pwnyaa: 時刻周りの修正

---

deploy/.eslintrc.json
deploy/index.ts
index.ts
package.json

* Typescript化
* ユーザー名にホスト名が含まれるよう修正
* ロード済みのボットがリアルタイムで表示されるように

Improve index.js

---

emoji-modifier/index.ts

runTransformaton() was renamed as createResult().
A smaller routine which strictly _runs transformation_ is newly defined as runTransformaton(), which is called in createResult().

runTransformaton() was renamed as buildResponse()

---

emoji-modifier/index.ts

emodi_help_2021Febの直し忘れです:bow:

Add semicolon

---

achievements/achievements.ts

added Understand achievements

---

channel-notifier/index.js

Hope to close #347 .
https://api.slack.com/methods/channels.invite
https://api.slack.com/methods/conversations.invite
動くやろの舞

channel-notifier: channels.invite -> conversations.invite

---

achievements/achievements.ts
pwnyaa/index.ts

- 取り敢えず参加しようというひと大歓迎なので、参加した人に実績を付与したいです。
- 難易度は、`pwnyaa-xyz-half`以下なので、`baby`にしました。

pwnyaa: joinしたことによる実績付与

---

pwnyaa/index.test.ts
pwnyaa/index.ts
pwnyaa/lib/BasicTypes.ts
pwnyaa/lib/CHManager.ts
pwnyaa/lib/TWManager.ts
pwnyaa/lib/XYZManager.ts

以下の機能追加及び修正を行いました
:new: cryptohack.orgに対応
:sparkles: 3種類ある常設CTFのプロファイル情報を統一
:sparkles: テストの追加
座禅くんだ後に、問題なさそうならばセルフマージします。

pwnyaa: Cryptohackに対応

---

pwnyaa/lib/CHManager.ts

~~close 422~~ 
**TODO**: 誤って解除された実績を戻せるなら、戻した後にセルフmergeします。

pwnyaa: cryptohackのスクレイピング時のバグ修正

---

index.ts

なんかスワップやたら減らんな〜と思ったのでたぶんこいつが悪い

Disable sharp cache

---

pwnyaa/index.test.ts
pwnyaa/index.ts
pwnyaa/lib/BasicTypes.ts

以下の変更を行いました。
:sparkles: statコマンドを追加  
:sparkles: LongestStreakの追加
🎨 重複機能の関数化
📝 helpコマンドの追加
test通り次第self-mergeします。

pwnyaa: statコマンド/streakの追加

---

hitandblow/index.ts

hitandblow:経過時間の小数点

---

pwnyaa/README.md
pwnyaa/index.test.ts
pwnyaa/index.ts
pwnyaa/lib/KSNManager.ts

以下の機能拡張を行いました。
- :sparkles: ksnctfに対応
- :ribbon:  諸々の表示をattachmentに
- :memo: READMEにチェックリストを追加
#432 のhakatashiさんのreview/mergeを待つ可能性もあるし、テスト通り次第self-mergeする可能性も有ります。

pwnyaa: 新機能追加(ksnctf/attachment)

---

pwnyaa/.eslintrc.json
pwnyaa/index.test.ts
pwnyaa/index.ts
pwnyaa/lib/BasicTypes.ts
pwnyaa/lib/KSNManager.ts

以下の機能修正を行いました。
- :bug: streaksの後方互換対応
- :bug: 誰も有効なstreaksを持っていない場合の表示対応
- :sparkles: ksnctfの問題をキャッシュ
- :ribbon: `check`コマンドをattachment対応
- :ribbon: `@pwnyaa`単体を`@pwnyaa help`と解釈
- :art: 各CTF-Managerで共通の処理を`Contest`インタフェースに追加。呼び出しをインタフェースを介して行う
テスト通り次第self-mergeします。

pwnyaa: 不具合修正・リファクタ

---

sushi-bot/index.js

Implement kasu-filter

---

pocky/index.js

ポッキーゲームを縦に圧縮

---

sushi-bot/index.js

Revert "Implement kasu-filter"

---

lib/__mocks__/slackUtils.ts

awaitしている実装なら良いですが、.then()で受け取っている部分のテストが正常に動かないため

lib/__mocks__/slackUtils.ts: async functionにした

---

.github/workflows/test.yml
achievements/index_production.ts
amongyou/index.ts
atcoder/index.ts
lib/.gitignore
lib/__mocks__/state.ts
lib/firestore.ts
lib/slack.ts
lib/slackUtils.ts
lib/state-file-to-firebase.js
lib/state.test.ts
lib/state.ts
lib/utils.ts
oogiri/index.ts
package-lock.json
package.json
tsconfig.json
wordhero/index.ts

Slackbot全体で使用できるステートライブラリlib/state.tsを実装

---

hangman/index.js

state.user -> state.challenger

---

achievements/achievements.ts
octas/index.ts

add octas achivements

---

hangman/index.js

hangmanの複数同時開催に対応しました。  
主な変更点は以下です: 
- :sparkles: 複数同時開催に対応
- :sparkles: challengerのスレッド外での反応を無視
- :zap: resetコマンドの結果を通知

hangman: 複数同時開催に対応

---

hangman/index.js

1回もミスらなかった解答を、褒める。
偉いね！！わーーい！！
resolves #463

hangman: パーフェクト解答を褒める

---

lyrics/index.test.ts
lyrics/index.ts

Update lyrics query

---

hangman/index.js

- add judge clue for perfect-solve
- in prev impl, gameover with time-over is regarded as perfect-solve.
- fix invalid syntax
- in prev impl, `!word` statement makes `slackid` of the playing user `undefined`.
fix #478

hangman: fix two separate bugs

---

pwnyaa/lib/XYZManager.ts

めんどくさいのでXYZしかエラーハンドリングしません。
fix #481

pwnyaa: handle connection error in XYZManager

---

better-custom-response/custom-responses.ts

昔一時期誰かが試しで作ってくれていたAかBか占いがpushされなさそうなので、アイデアを借りてフクキタルに占わせるbotを作りました

bcr: (.+か)+占いbot (by マチカネフクキタル) を追加

---

discord/index.ts
discord/tts.ts

今後ユーザー辞書の登録なども見据えてstateで辞書を管理している

discord TTS で一部の単語を置き換えて読み上げる, URL省略

---

discord/hayaoshi.ts

enum Voice型の引数にstringを与えていたので修正

bugfix: tried to assign str to enum

---

pwnyaa/lib/KSNManager.ts

Dateをnewで一気に設定

---

.github/workflows/test.yml
discord/tts.ts
hitandblow/.eslintrc.json
package-lock.json
package.json

reviewdogを高速化

---

hangman/index.js

- it tried to destructure null.
fix #504

hangman: fix bug

---

discord/hayaoshiUtils.ts

読み上げピッチの変更を「…対し、…」形式のクイズにも適用します

Discord: change pitch in "対し"

---

.gitpod.yml

Add configuration for GitPod

---

discord/index.ts

GitPodからプルリク作るテスト2
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/520"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

discord: Configure TTS to correctly detect space after URL

---

discord/speeches/voicevox.ts
discord/tts.ts

close #530 
外部APIからのレスポンスが遅いときに後続のクエリが詰まる問題を修正
state管理と音声再生の部分だけをmutexにした
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/531"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

TTSのmutexスコープを縮める

---

tsconfig.json

replaceAllを使いたいので
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/538"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

tscongfigのlibをes2020からes2021に変更

---

CODEOWNERS
achievements/achievements.ts
discord/hayaoshi.ts
index.ts
topic/.eslintrc.json
topic/index.ts

* :koresuki:が5個以上ついた「短文の」メッセージを自動的にtopicに設定します。
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/542"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add topic bot

---

kirafan/quiz.ts

- lodashのrandom関数が閉区間だと知ったので、なおした
- まだたまにアップロードがタイムアウトするようなので、画像のアップロードを直列処理にした

きらファン当てクイズ バグ修正&仕様変更

---

pwnyaa/lib/XYZManager.ts

一文字の中でも、更に小さいこの文字の存在の欠如さえ、世界に歪みをもたらす可能性が有る。
これは、そんな物語。。。
2022年4月公開予定!!
fix #554 
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/557"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

pwnyaa: fix typo

---

discord/speeches/index.ts
discord/speeches/voicevox.ts

新しい声2つ
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/561"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

new voice: tsumugi and ritsu in voicevox

---

CODEOWNERS
adventar/.eslintrc.json
adventar/.gitignore
adventar/.prettierrc.json
adventar/index.ts
index.ts

タイトルのとおりです
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/563"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

[add] Adventar のアドカレを定期的にスクレイピングして更新を知らせるbot

---

discord/speeches/index.ts
discord/speeches/voicevox.ts
discord/tts.ts

Ref #570 
本当はCloseしたいがhayaoshiにも該当箇所があるっぽいのでそこをなおすまでCloseしないことにする
あとtts voicesで出てくるvoicevoxのproviderがおかしかったので修正 & voicevoxのリファクタリング
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/571"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

bugfix of Discord TTS: avoid speech interruption & description of "tts voices"

---

slack-log/index.ts

part of #424 
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/575"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

slack-log: s/rtm/event/ in test

---

lib/loadFont.ts

Noto Fonts のリンクが変わってたので更新
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/573"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

lib: Update the link of Noto Fonts

---

welcome/index.ts

part of #424 
TODO:
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/576"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

welcome: deprecate rtm

---

sunrise/index.js

Resolve #578 
partially revert e2eb2a2cc397076b946fab86ab26c33af3eb8a4b
これいると思います
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/579"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

sunrise: tick tick

---

context-free/index.ts

part of #424 
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/584"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

context-free: deprecate rtm

---

hayaoshi/index.ts

part of #424 
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/591"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

hayaoshi: deprecate rtm

---

mahjong/index.js

part of #424 
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/594"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

mahjong: deprecate rtm

---

sunrise/index.js

part of #424 
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/603"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

sunrise: deprecate rtm

---

hakatashi-visor/index.ts

part of #424 
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/589"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

hakatashi-visor: deprecate rtm

---

pwnyaa/index.ts

part of #424 
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/599"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

pwnyaa: deprecate rtm

---

room-gacha/index.ts

part of #424 
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/600"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

room-gacha: deprecate rtm

---

lyrics/index.ts

part of #424 
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/593"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

lyrics: deprecate rtm

---

emoxpand/index.ts

part of #424 
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/586"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

emoxpand: deprecate rtm

---

summary/index.js

part of #424 
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/602"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

summary: deprecate rtm

---

taiko/index.ts

part of #424 
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/604"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

taiko: deprecate rtm

---

pocky/index.js

part of #424 
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/597"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

pocky: deprecate rtm

---

better-custom-response/index.ts

part of #424 
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/588"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

better-custom-response: deprecate rtm

---

checkin/index.js
checkin/index.test.js

part of #424 
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/583"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

checkin: deprecate rtm

---

octas/index.ts

part of #424 
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/595"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

octas: deprecate rtm

---

golfbot/index.ts

part of #424 
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/587"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

golfbot: deprecate rtm

---

sorting-riddles/index.ts

part of #424 
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/601"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

sorting-riddles: deprecate rtm

---

kirafan/quiz.ts

part of #424 
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/592"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

kirafan: deprecate rtm

---

voiperrobot/index.ts

part of #424 
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/607"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

voiperrobot: deprecate rtm

---

wordhero/index.ts

part of #424 
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/608"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

wordhero: deprecate rtm

---

hangman/index.js

part of #424 
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/590"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

hangman: deprecate rtm

---

dajare/index.js
dajare/index.test.js

part of #424 
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/585"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

dajare: deprecate rtm

---

ahokusa/index.js

part of #424 
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/580"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

ahokusa: deprecate rtm

---

ponpe/index.ts

part of #424 
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/598"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

ponpe: deprecate rtm

---

tiobot/index.ts

part of #424 
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/605"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

tiobot: deprecate rtm

---

vocabwar/index.js
vocabwar/index.test.js

part of #424 
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/606"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

vocabwar: deprecate rtm

---

anime/anison.js
anime/index.js
anime/namori.ts

part of #424 
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/581"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

anime: deprecate rtm

---

atcoder/index.ts

part of #424 
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/582"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

atcoder: deprecate rtm

---

emoji-modifier/index.ts

part of #424
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/611"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

emoji-modifier: deprecate rtm

---

prime/index.js

part of #424
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/613"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

prime: deprecate rtm

---

nojoin/index.ts

part of #424
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/612"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

nojoin: deprecate rtm

---

shogi/index.js

part of #424
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/615"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

shogi: deprecate rtm

---

discord/index.ts

part of #424
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/610"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

discord: deprecate rtm

---

.env.example
deploy/index.ts
package-lock.json
package.json

Resolve #609 
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/617"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

deploy: GitHub webhook validate

---

ricochet-robots/index.js

part of #424
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/614"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

ricochet-robots: deprecate rtm

---

sushi-bot/index.js
sushi-bot/index.test.js

🎉 
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/625"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

sushi-bot: s/cookies146/shaved_ice/

---

tahoiya/index.js

part of #424 
これはたぶん(9割)なんですが、RTMであったtyping indicatorはevents apiでサポートされなくなりました。typing indicatorはSlack internalなものとなり、ユーザーには使えなくしたいのかなーと想像しています。
1. https://api.slack.com/rtm#typing_indicators
2. https://api.slack.com/events/user_typing
> Works with `RTM`
3. https://api.slack.com/authentication/migration#faq_permissions_event_differences
> Events API does not make the typing indicator available
このため、もともとtahoiyaにあった `sendTyping()` が消されます。
`sendTyping()` は、https://github.com/tsg-ut/slackbot/commit/2f304ce09c96e8ddcf52fbd0bd097c64647b67d7 において導入されました。tahoiya botに意味を尋ねた後、実際に結果が出てくるまで少し時間がかかるので、尋ねている人が無視されたんじゃないかと誤解してもう一度聞き直し、F5アタック的に負荷が上がる対策な気がします。
とりあえず一度RTMの排除にあたってこのロジックは消して、もし必要ならば、slackbot起動時の状況投稿のような感じで、editしていくみたいな実装したらいいんじゃないかな～と思います（まあ、最近tahoiyaあんまりされているイメージないし、誰かがやる気になったらやればいいんじゃね、という気持 …

[BREAKING CHANGE] tahoiya: deprecate rtm; remove sendTyping

---

topic/index.ts

part of #424 
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/622"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

topic: deprecate rtm

---

emoji-notifier/index.js
emoji-notifier/index.test.js

part of #424 
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/621"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

emoji-notifier: deprecate rtm

---

channel-notifier/index.js
channel-notifier/index.test.js

part of #424 
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/620"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

channel-notifier: deprecate rtm

---

oogiri/index.ts

part of #424 
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/619"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

oogiri: deprecate rtm

---

hitandblow/index.ts

part of #424 
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/628"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

hitandblow: deprecate rtm

---

atequiz/index.ts
bungo-quiz/index.ts
hitandblow/index.ts

quiz: deprecate rtm

---

adventar/index.ts

part of #424 
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/626"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

adventar: deprecate rtm

---

achievements/index_production.ts

part of #424 
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/630"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

achievements: deprecate rtm

---

amongyou/index.ts

part of #424 
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/627"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

amongyou: deprecate rtm

---

tunnel/index.ts

part of #424 
Events API payload schema ref: https://api.slack.com/types/event
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/631"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

tunnel: deprecate rtm

---

api/index.ts
lib/slackUtils.ts

getAllTSGMembers

---

index.ts
lib/slack.ts
lib/slackEventClient.ts
tunnel/index.ts

Resolve #638
Retry #643
ぴえー
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/644"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

TSGEventClient

---

context-free/index.ts

たほいやbotを利用して嘘の説明文をpostします
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/650"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

context-free: エイプリルフール限定で「通りすがりおじさん」が嘘の説明文をpostする

---

amongyou/index.ts
atequiz/index.ts
oogiri/index.ts
tsconfig.json

ciのtsc check、実は全然うごいてなかったっぽいです？
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/651"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

ci: type check

---

better-custom-response/index.ts

* ちゃんとドキュメント読みましょうね〜
* ちゃんとレビューしましょうね〜
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/655"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

bcr をスレッド対応 (訂正版)

---

atequiz/index.ts
mahjong/index.js

@settyan117 judgeの第二引数にユーザーIDを渡すようにしました (レビューお願いします)
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/662"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

mahjong: チンイツクイズの回答数を一人一回までに制限

---

anime/namori.ts

あと「なもり当てクイズ」を「キャラ当てクイズ」にリネーム
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/665"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

anime/namori: Ixyさんのイラストをなもり当てクイズのソースに追加

---

lib/slackMock.js
welcome/index.test.ts
welcome/index.ts

welcome botの機能は自明でないため、welcome bot自体の説明文をscrapboxに追加したいです。
するとwelcome messageにも表示されてしまうので、コメント記法を追加し、welcomeライターへのメッセージをそこに追加します。
コメントのプリフィクスは、 `///` です。なんとなく。←というような説明がコメントに追加されます。
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/667"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

welcome: add comment syntax

---

ricochet-robots/index.js

:pensive:
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/672"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

[fix] roundをimportした

---

ricochet-robots/index.js

何度もすみません…
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/673"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

[fix] ヤバイところなおした

---

ricochet-robots/index.js

ずび
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/674"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

[fix] バカと申します

---

index.ts
lib/slack.ts
lib/slackMock.js
package-lock.json
package.json

Resolve #424 Resolve #555
👋 
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/678"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

rm rtm-api

---

package-lock.json
package.json

NOTE: This should be reverted after the pull request discordjs/discord.js#7999 is merged into the main branch
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/680"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Update discord.js to the version with text-in-voice

---

sushi-bot/index.js
sushi-bot/index.test.js

最近は、lib/stateっていうやつが流行ってるらしい
あと、ランキングがしょっちゅう狂ってるきもするんだよね
マージするとその週のデータが消し飛びますが別に大丈夫でしょ
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/683"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

sushi-bot: use lib/state

---

welcome/index.ts

logから、ちゃんとuserの型がわかったので
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/686"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

welcome: use team_join event

---

discord/speeches/index.ts
discord/speeches/voicevox.ts

「九州そら」（感情付き）
「九州そら」（ささやきVer）
「もち子さん」
の追加
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/691"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

add newvoice from voicevox 12

---

.firebaserc
firebase.json
firestore.indexes.json
firestore.rules

Ref: #692
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/695"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add firestore configuration files

---

atequiz/index.ts

postする内容がないときはnullにすればよいようにした
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/698"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

[update] immediateMessage と answerMessage を null 許容にした

---

ricochet-robots/index.js
ricochet-robots/index.test.js

とりあえず解いている問題が上書きされないようにしました。
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/707"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

ricochet-robots: fix problem overwrite bug

---

.github/workflows/test.yml

Close #699 
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/714"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

ci: test rust in gh actions

---

welcome/index.test.ts
welcome/index.ts

Close #670 
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/715"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

welcome: use code api

---

channel-notifier/index.js
lib/slackMock.js
scrapbox/index.test.ts
scrapbox/index.ts
slack-log/index.test.ts
slack-log/index.ts
topic/index.ts

#717 
channel:manage を setTopic のために足した
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/720"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

redule hakatashi token

---

.env.example
index.ts
slow-quiz/.eslintrc.json
slow-quiz/index.ts
slow-quiz/views/answerQuestionDialog.ts
slow-quiz/views/registerQuizDialog.ts

<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/721"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

1日1文字クイズを実装

---

mail-hook/index.js
scrapbox/index.ts

loggerにbot名を入れたいなー
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/722"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

scrapbox: logger

---

slow-quiz/index.ts
slow-quiz/views/listAnswersDialog.ts
slow-quiz/views/listQuizDialog.ts

<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/725"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

slow-quiz: Implement several features

---

hangman/index.js

hangman ゲーム終了時、単語の定義をリプライする機能を追加
https://dictionaryapi.dev/ を利用しています
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/719"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Hangman definition

---

index.ts

ぶどう
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/728"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

logging in index

---

lib/slackCache.ts

#726 がマージされたらマージできる
https://github.com/slackapi/node-slack-sdk/commit/3e9c483c593d6aa28f6f5680f287722df3327609
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/729"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

slackcache: correct type!

---

slow-quiz/index.ts
slow-quiz/views/answerQuestionDialog.ts
slow-quiz/views/gameDetailsDialog.ts
slow-quiz/views/listAnswersDialog.ts
slow-quiz/views/postCommentDialog.ts

<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/735"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

slow-quiz: Implement comment feature

---

slow-quiz/index.ts
slow-quiz/views/answerQuestionDialog.ts
slow-quiz/views/postCommentDialog.ts

slow-quiz: Implement instant comment feature

---

tahoiya/index.js

https://github.com/tsg-ut/slackbot/issues/737
こんな感じになります　ただし何も試してないです　うごくといいね
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/738"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

tahoiya: try as_user catch

---

bin/migrate-slow-quiz.ts
slow-quiz/index.ts
slow-quiz/views/answerQuestionDialog.ts
slow-quiz/views/footer.ts
slow-quiz/views/gameDetailsDialog.ts
slow-quiz/views/listAnswersDialog.ts
slow-quiz/views/postCommentDialog.ts
slow-quiz/views/registerQuizDialog.ts

<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/746"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Slow quiz: genre and improvement

---

atequiz/index.ts

不正解時にメッセージで反応することもできるようになりました。
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/747"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

incorrectMessage added in atequiz

---

achievements/achievements.ts
map-guessr/index.ts

mutexがロックしっぱなしにならないようにしました。
latLngDeformatがエラー吐いてたので修正。
実績の格下げ。
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/755"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Map guessr small fix

---

firestore.rules

firestore: Allow access to users collection

---

sushi-bot/index.test.js
sushi-bot/index.ts

もうだいぶTSがデファクトスタンダードになってるとおもってます
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/760"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

sushi-bot: type

---

.github/workflows/test.yml
functions/.gitignore
functions/.runtimeconfig.example.json
functions/package-lock.json
functions/package.json
functions/src/index.ts
functions/src/jobs/slackFileArchiveCronJeb.test.ts
functions/src/jobs/slackFileArchiveCronJob.ts
functions/tsconfig.json
package-lock.json
package.json

tsgbotリポジトリで実装されている[slack-files-archiver](https://github.com/tsg-ut/tsgbot/blob/master/slack-file-archiver.js)ジョブを Firebase Functions に移行。
その他微妙な修正をいくつか
テストも追加してみようかな
Ref: tsg-ut/tsgbot#5
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/765"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

functions: Migrate slack-files-archiver function

---

atequiz/index.ts
index.ts
map-guessr/index.ts

* 画像のポスト先をスレッド内に変更
* Googleマップのリンクのunfurlを消去
* Googleマップのリンクをインラインリンクに
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/767"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

座標当てクイズをちょっと静かにする

---

character-quiz/index.ts

クイズを起動した人の実績にカウントされるようになっていたので、なおしました。
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/773"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

[fix] 実績の解除対象を修正

---

discord/speeches/index.ts
discord/speeches/voicevox.ts

剣崎さん、ささやきずんだもんを追加
<a href="https://gitpod.io/#https://github.com/tsg-ut/slackbot/pull/772"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

add voicevox speakers

---

lib/state.ts

lib/state: DBのアップデート後にローカルの変更リストが消去されていないバグを修正 (Ref: #771)

---

achievements/achievements.ts
hangman/index.js

add hangman-de-hangman achievement

---

mahjong/index.js

#553  で要望されていたコマンドを、ドラ表示の方だけ「ドラ牌」として先に実装しました。

Mahjong command implement

---

discord/hayaoshi.ts
discord/speeches/index.ts

discord: GCP TTS の新しいボイスを追加

---

CODEOWNERS
index.ts
shmug/.eslintrc.json
shmug/.prettierrc.json
shmug/index.ts

/shmug を追加

---

.env.example
CODEOWNERS
index.ts
mackerel/.editorconfig
mackerel/.eslintrc.json
mackerel/const.ts
mackerel/index.ts
mackerel/views/view.ts
package-lock.json
package.json

新bot、`mackerel` です。
Mackerelにはユーザーを招待するAPIがあります。 https://mackerel.io/ja/api-docs/entry/invitations#create
あんまり公式ではなさそうですがnpmがあったのでそれを使います。 https://www.npmjs.com/package/mackerel/v/0.1.1
emailをModalの入力欄によって取得し、そのemailに向かって招待を行います。

mackerel: invite

---

mahjong/index.js

#553 
画像が何らかの原因で取ってこられなかったときのために、手牌表示コマンドを実装した。
採譜表示で12r588m239p467s東白白のように表記。
ドラ表示牌コマンドと統合した。

Mahjong 手牌表示 implement

---

achievements/achievements.ts
slow-quiz/index.ts

1人以上に正解された状態で完走（問題文がすべて表示される）した問題の作者に実績を与えます．
正直あまりいいコードではないんですが，こう書くしかないような気がする．

slow-quiz: 完走実績の追加

---

ahokusa/index.js

変更点
- あほくさプレイ中の盤面や正解などがsandbox本体に流れないようにした。
- プレイ中に他の人が起動しようとするとstateを上書きしてしまうので、「既に${url}で起動中だよ」というリプライを付けてstateが上書きされないようにした。
- ↑のままだとプレイ中のスレッドが放置されて消えてしまった場合に困るので、『スライドパズル爆破』もしくは『あ　ほ　く　さ』とpostすることによってstateをリセットできるようにした。

ahokusa: プレイ中の投稿がbroadcastされないようにする

---

package-lock.json
package.json

Upgrade @discordjs/voice to v0.15.0

---

.env.example
index.ts
package-lock.json
package.json
pilot/.eslintrc.json
pilot/index.ts

Scrapboxの[pilot](https://scrapbox.io/tsg/pilot)のページの内容をもとに、 #自己紹介 にポストされたテキストに基づいて自動でチャンネルをおすすめします

Add pilot bot

---

index.ts
package-lock.json
package.json
qrcode-quiz/.eslintrc.json
qrcode-quiz/index.ts

Add qrcode-quiz

---

achievements/achievements.ts
qrcode-quiz/index.ts

* 実績をいくつか追加
* 回答時間を表示
* hard問題の出題時のバグ修正
* クソデカimageがsandboxにpostされないように修正
* isUnmasked => masked
* kanjiモードで漢字だけを出題するよう修正

QR当てクイズの改良

---

.env.example
lib/slackMock.js
sunrise/fetch.ts
sunrise/index.ts
sunrise/views/footer.ts
sunrise/views/listPointsDialog.ts
sunrise/views/registerPointDialog.ts

sunrise: Implement minutecast

---

lib/slackMock.js
sushi-bot/index.test.js
sushi-bot/index.ts

* "twitter"を含む投稿に:x-logo:リアクションをつけるよう修正
* ついでにslackMockのメソッドコールをjest.fn()でモックできるように

sushi-bot: Add :x-logo: reaction to posts containing 'twitter'

---

sushi-bot/index.test.js
sushi-bot/index.ts

Closes #186 .
リンクのプレビューなど、後で追加された attachment も対応

attachment内の寿司に対応

---

character-quiz/index.ts

名前がないキャラクターに対応

---

atequiz/index.ts

start メソッドの引数にオプションを受け取る余地を与え，解答者を一人に限定するソロモードをオプションで選べるようにした

[add] 一人プレイモードを実装

---

auto-archiver/.eslintrc.json
auto-archiver/index.test.ts
auto-archiver/index.ts
index.ts
lib/__mocks__/state.ts
lib/slackMock.ts

必要になりそうなので、必要な時に使えるように実装しておきました。
↓ボタンを押すと

90日間投稿のないチャンネルをアーカイブするBOTを作成

---

discord/notifier.test.ts
discord/notifier.ts

直近3分間のDiscordのイベントを1つのメッセージにまとめる

---

achievements/index_production.ts
ricochet-robots/SinglePlayRicochetRobot.ts

ハイパーロボットの実績解除条件がおかしいので修正

---

.github/workflows/test.yml
city-symbol/.eslintrc.json
city-symbol/index.ts
index.ts

Implement city-symbol bot

---

city-symbol/index.ts

city-symbol: 基礎自治体位置図テンプレートの省略記法に対応

---

city-symbol/index.ts

city-symbol: Improve display format of answer

---

.devcontainer/compose.yaml
.github/workflows/codespaces-image.yml
README.md

* Before: 8分01秒
* After: 5分48秒

devcontainer: Dockerイメージを事前ビルドしCodespacesの起動を高速化

---

city-symbol/index.ts

city-symbol: Add AI hint sources section to answerMessage

---

CODEOWNERS
index.ts
nmpz/.eslintrc.json
nmpz/.gitignore
nmpz/.prettierrc.json
nmpz/index.ts

nmpz: Implement nmpz bot

---

achievements/achievements.ts
nmpz/index.ts

nmpz: Added achievements

---

pwnyaa/index.test.ts
pwnyaa/index.ts

#983 によって起動がバカ重くなったので仕方なくテスト環境でのみ初期化を待つよう修正

pwnyaa: Await for initialization only in unit test

---

functions/src/jobs/slackFileArchiveCronJeb.test.ts
functions/src/jobs/slackFileArchiveCronJob.ts

functions: Add ts_to field to files.list call

---

sushi-bot/index.ts

sushi-bot: Add fall through comment to switch statements

---

package-lock.json

Critical vulnerabilities から減らしていこうキャンペーン実施中

npm audit fix vm2

---

.env.example
lib/slackCache.test.ts
lib/slackCache.ts
lib/slackPatron.ts
lib/slackUtils.ts
oneiromancy/index.ts
slack-log/index.ts
topic/index.test.ts
topic/index.ts
tunnel/index.ts

Slackのconversations系メソッドの呼び出しにslack-patronを利用するよう修正

---

mail-hook/index.ts
oneiromancy/index.ts
slow-quiz/index.ts

GPT-4o mini のほうが高性能で安い
ついでにslow-quizをちょっとリファクタリングした

GPT-3.5を使用していた箇所をGPT-4o miniに置き換え

---

.github/workflows/gemini-pr-review.yml

せっかく GitHub Actions も Gemini CLI も無料で使えるので、ばしばし使っていこう

Add gemini-pr-review workflow

---

.github/workflows/gemini-pr-review.yml
auto-archiver/index.test.ts
auto-archiver/index.ts

- 既にメッセージが存在するチャンネルに再度メッセージをポストしないよう修正
- 1日後に再度判定した際に24時間以内に返答がないとみなされない問題を修正
- ロック用のスイッチ処理を削除

auto-archiver: バグ修正など

---

tahoiya/index.js

tahoiya bug fix url（すいません一箇所間違えた. sqlのtableはcolumn名urlですから...）

tahoiya bug fix
